### ISSUE TITLE
Retrieve environment variable.

### ISSUE THREAD

**Issue by tgxworld** [SamSaffron/pups#11]
Hi @SamSaffron! 

Is there a way to retrieve environment variables from within Pups? If not, is it a feature that you would like to have implemented?

**Comment by SamSaffron** [comment]
I thought I had this, have a look at the tests? if not, sure, please add it.

**Comment by tgxworld** [comment]
@SamSaffron Aren't you listening to DHH's talk right now? :stuck_out_tongue:

**Comment by SamSaffron** [comment]
sort of ... I don't really need to listen now its the "turbolinks 3" part
of the talk.

**Comment by tgxworld** [comment]
Ah the feature has indeed [been implemented](https://github.com/SamSaffron/pups/blob/master/test/config_test.rb#L7). I'll add it to the documentation :)
